package practice.hanchen.kknews;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CHANNEL".
 */
public class Channel {

    private Long id;
    /** Not-null value. */
    private String title;
    /** Not-null value. */
    private String URL;

    public Channel() {
    }

    public Channel(Long id) {
        this.id = id;
    }

    public Channel(Long id, String title, String URL) {
        this.id = id;
        this.title = title;
        this.URL = URL;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(String title) {
        this.title = title;
    }

    /** Not-null value. */
    public String getURL() {
        return URL;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setURL(String URL) {
        this.URL = URL;
    }

}
