package practice.hanchen.kknews;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import practice.hanchen.kknews.PersonalFolder;
import practice.hanchen.kknews.PersonalList;

import practice.hanchen.kknews.PersonalFolderDao;
import practice.hanchen.kknews.PersonalListDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig personalFolderDaoConfig;
    private final DaoConfig personalListDaoConfig;

    private final PersonalFolderDao personalFolderDao;
    private final PersonalListDao personalListDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        personalFolderDaoConfig = daoConfigMap.get(PersonalFolderDao.class).clone();
        personalFolderDaoConfig.initIdentityScope(type);

        personalListDaoConfig = daoConfigMap.get(PersonalListDao.class).clone();
        personalListDaoConfig.initIdentityScope(type);

        personalFolderDao = new PersonalFolderDao(personalFolderDaoConfig, this);
        personalListDao = new PersonalListDao(personalListDaoConfig, this);

        registerDao(PersonalFolder.class, personalFolderDao);
        registerDao(PersonalList.class, personalListDao);
    }
    
    public void clear() {
        personalFolderDaoConfig.getIdentityScope().clear();
        personalListDaoConfig.getIdentityScope().clear();
    }

    public PersonalFolderDao getPersonalFolderDao() {
        return personalFolderDao;
    }

    public PersonalListDao getPersonalListDao() {
        return personalListDao;
    }

}
