package practice.hanchen.kknews;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PERSONAL_LIST".
 */
public class PersonalList {

    private Integer folderId;
    /** Not-null value. */
    private String title;
    /** Not-null value. */
    private String picURL;

    public PersonalList() {
    }

    public PersonalList(Integer folderId, String title, String picURL) {
        this.folderId = folderId;
        this.title = title;
        this.picURL = picURL;
    }

    public Integer getFolderId() {
        return folderId;
    }

    public void setFolderId(Integer folderId) {
        this.folderId = folderId;
    }

    /** Not-null value. */
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(String title) {
        this.title = title;
    }

    /** Not-null value. */
    public String getPicURL() {
        return picURL;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPicURL(String picURL) {
        this.picURL = picURL;
    }

}
