package practice.hanchen.kknews;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PERSONAL_FOLDER".
 */
public class PersonalFolder {

    private Long id;
    /** Not-null value. */
    private String folderName;
    /** Not-null value. */
    private String defaultPicUrl;

    public PersonalFolder() {
    }

    public PersonalFolder(Long id) {
        this.id = id;
    }

    public PersonalFolder(Long id, String folderName, String defaultPicUrl) {
        this.id = id;
        this.folderName = folderName;
        this.defaultPicUrl = defaultPicUrl;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getFolderName() {
        return folderName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFolderName(String folderName) {
        this.folderName = folderName;
    }

    /** Not-null value. */
    public String getDefaultPicUrl() {
        return defaultPicUrl;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDefaultPicUrl(String defaultPicUrl) {
        this.defaultPicUrl = defaultPicUrl;
    }

}
