package practice.hanchen.kknews;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PERSONAL_LIST".
 */
public class PersonalList {

    private Long id;
    private long folderId;
    private long articleId;

    public PersonalList() {
    }

    public PersonalList(Long id) {
        this.id = id;
    }

    public PersonalList(Long id, long folderId, long articleId) {
        this.id = id;
        this.folderId = folderId;
        this.articleId = articleId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getFolderId() {
        return folderId;
    }

    public void setFolderId(long folderId) {
        this.folderId = folderId;
    }

    public long getArticleId() {
        return articleId;
    }

    public void setArticleId(long articleId) {
        this.articleId = articleId;
    }

}
