package practice.hanchen.kknews;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import practice.hanchen.kknews.PersonalList;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PERSONAL_LIST".
*/
public class PersonalListDao extends AbstractDao<PersonalList, Void> {

    public static final String TABLENAME = "PERSONAL_LIST";

    /**
     * Properties of entity PersonalList.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property FolderId = new Property(0, Integer.class, "folderId", false, "FOLDER_ID");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property PicURL = new Property(2, String.class, "picURL", false, "PIC_URL");
    };


    public PersonalListDao(DaoConfig config) {
        super(config);
    }
    
    public PersonalListDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PERSONAL_LIST\" (" + //
                "\"FOLDER_ID\" INTEGER," + // 0: folderId
                "\"TITLE\" TEXT NOT NULL ," + // 1: title
                "\"PIC_URL\" TEXT NOT NULL );"); // 2: picURL
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PERSONAL_LIST\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, PersonalList entity) {
        stmt.clearBindings();
 
        Integer folderId = entity.getFolderId();
        if (folderId != null) {
            stmt.bindLong(1, folderId);
        }
        stmt.bindString(2, entity.getTitle());
        stmt.bindString(3, entity.getPicURL());
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public PersonalList readEntity(Cursor cursor, int offset) {
        PersonalList entity = new PersonalList( //
            cursor.isNull(offset + 0) ? null : cursor.getInt(offset + 0), // folderId
            cursor.getString(offset + 1), // title
            cursor.getString(offset + 2) // picURL
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, PersonalList entity, int offset) {
        entity.setFolderId(cursor.isNull(offset + 0) ? null : cursor.getInt(offset + 0));
        entity.setTitle(cursor.getString(offset + 1));
        entity.setPicURL(cursor.getString(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(PersonalList entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(PersonalList entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
