package practice.hanchen.kknews.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import practice.hanchen.kknews.dao.PersonalFolder;
import practice.hanchen.kknews.dao.PersonalList;
import practice.hanchen.kknews.dao.Channel;
import practice.hanchen.kknews.dao.Article;

import practice.hanchen.kknews.dao.PersonalFolderDao;
import practice.hanchen.kknews.dao.PersonalListDao;
import practice.hanchen.kknews.dao.ChannelDao;
import practice.hanchen.kknews.dao.ArticleDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig personalFolderDaoConfig;
    private final DaoConfig personalListDaoConfig;
    private final DaoConfig channelDaoConfig;
    private final DaoConfig articleDaoConfig;

    private final PersonalFolderDao personalFolderDao;
    private final PersonalListDao personalListDao;
    private final ChannelDao channelDao;
    private final ArticleDao articleDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        personalFolderDaoConfig = daoConfigMap.get(PersonalFolderDao.class).clone();
        personalFolderDaoConfig.initIdentityScope(type);

        personalListDaoConfig = daoConfigMap.get(PersonalListDao.class).clone();
        personalListDaoConfig.initIdentityScope(type);

        channelDaoConfig = daoConfigMap.get(ChannelDao.class).clone();
        channelDaoConfig.initIdentityScope(type);

        articleDaoConfig = daoConfigMap.get(ArticleDao.class).clone();
        articleDaoConfig.initIdentityScope(type);

        personalFolderDao = new PersonalFolderDao(personalFolderDaoConfig, this);
        personalListDao = new PersonalListDao(personalListDaoConfig, this);
        channelDao = new ChannelDao(channelDaoConfig, this);
        articleDao = new ArticleDao(articleDaoConfig, this);

        registerDao(PersonalFolder.class, personalFolderDao);
        registerDao(PersonalList.class, personalListDao);
        registerDao(Channel.class, channelDao);
        registerDao(Article.class, articleDao);
    }
    
    public void clear() {
        personalFolderDaoConfig.getIdentityScope().clear();
        personalListDaoConfig.getIdentityScope().clear();
        channelDaoConfig.getIdentityScope().clear();
        articleDaoConfig.getIdentityScope().clear();
    }

    public PersonalFolderDao getPersonalFolderDao() {
        return personalFolderDao;
    }

    public PersonalListDao getPersonalListDao() {
        return personalListDao;
    }

    public ChannelDao getChannelDao() {
        return channelDao;
    }

    public ArticleDao getArticleDao() {
        return articleDao;
    }

}
